### ISSUE TITLE
Support for Analog Outputs

### ISSUE THREAD

**Issue by CaPlasberg** [ros-drivers/phidgets_drivers#102]
I've noticed Analog Outpts as e.g. Board 1002_0B aren't supported right now. It might be usefull to also support them. Have a look [here](https://github.com/CaPlasberg/phidgets_drivers/tree/add_analog_outputs) for a solution similar to Digital Outputs.

**Comment by clalancette** [comment]
Agreed!  If you'd like to open a pull request adding that, we'd be happy to review it.

**Comment by mintar** [comment]
Closed by #103.
