### ISSUE TITLE
Port #127 to ROS2 (Add support for VINT networkhub)

### ISSUE THREAD

**Issue by mintar** [ros-drivers/phidgets_drivers#135]
See #127

**Comment by patilunmesh** [comment]
Any update on this!? Is there a way to use ROS 2 with VINT hub? @mintar

**Comment by mintar** [comment]
I've written a PR that should fix this: #172.

@patilunmesh, could you please test whether the PR works with the VINT hub and report back? Then I can merge it.

**Comment by patilunmesh** [comment]
@mintar,  I can test this but at the first look it seems like it needs some changes in phidgets22.cpp, openWaitForAttachment function. I will get back once I test this.

**Comment by mintar** [comment]
It works on Noetic like this (with the temperature phidget), so I'm pretty confident it should work on ROS2 as well. I'm looking forward to hearing your results!

**Comment by mintar** [comment]
Fixed via #172.
