### ISSUE TITLE
Out-of-order packets

### ISSUE THREAD

**Issue by alexwhittemore** [ros-drivers/phidgets_drivers#17]
Here's another one I hope to characterize better tomorrow, but I want to get it written in case anyone's seen this behavior before: it appears sometimes that the driver publishes IMU messages to the topic out-of-order in time. That is, a message will hit the topic with an earlier capture time than the most recent, as if there's a race condition somewhere in the pipeline ahead of publishing. In most applications, this probably doesn't matter much, but for whatever reason, Cartographer chooses to handle it with an instant choke-and-die.

**Comment by mintar** [comment]
That sounds like a bug. If you can reproduce it, it would be great to have a rosbag of this (also for the other issues).

**Comment by alexwhittemore** [comment]
That I can do! I'll get one today.
