### ISSUE TITLE
Add @clalancette to phidgets-maintainers

### ISSUE THREAD

**Issue by mintar** [ros-drivers/phidgets_drivers#45]
Hi @jack-oquin (or anybody else with the required privileges), could you please add @clalancette to the @ros-drivers/phidgets-maintainers team? He will work on the ROS2 port of phidgets_drivers.

**Comment by clalancette** [comment]
All right, thanks to @wjwwood, I have permissions to this repository now.  I'll close this out, and I'll soon create a dashing branch (it may have to wait until early next week).
