### ISSUE TITLE
PhidgetDCMotor_getBackEMF Operation Not Supported Error in dashing branch

### ISSUE THREAD

**Issue by peterpolidoro** [ros-drivers/phidgets_drivers#50]
@clalancette nice work on the upgrade to Phidget22 in the dashing branch, thank you!

I was playing with a DC Motor Phidget and I noticed that although the DCMotor class API lists getBackEMF, none of the DC Motor Phidget APIs actually seem to support that function. So when I run your code I get a "[component_container-1] [ERROR] [phidgets_motors]: Motors: Failed to get back EMF for Motor channel 0: Operation Not Supported" error.

I am happy to help you fix this or to do more testing if you do not have time. In ROS, is it better practice to not even create a publisher on an unsupported topic or is it better to publish some dummy value?

**Comment by clalancette** [comment]
> @clalancette nice work on the upgrade to Phidget22 in the dashing branch, thank you!

You are welcome.

> 
> I was playing with a DC Motor Phidget and I noticed that although the DCMotor class API lists getBackEMF, none of the DC Motor Phidget APIs actually seem to support that function. So when I run your code I get a "[component_container-1] [ERROR] [phidgets_motors]: Motors: Failed to get back EMF for Motor channel 0: Operation Not Supported" error.

Hm, interesting.  I'm pretty sure I tested it at one point and it worked with the Motor Phidget I had, but that was a while ago.  I'll have to go back and test it again (probably next week).

> 
> I am happy to help you fix this or to do more testing if you do not have time. In ROS, is it better practice to not even create a publisher on an unsupported topic or is it better to publish some dummy value?

Yeah, I think it would be best for you to fix it and open a PR, as I have no good way to test it.  As far as whether it is better to not publish or publish a dummy value, it is kind of a case-by-case basis.  In this case I think it is most consistent with the rest of this driver to just not create the publisher at all.  That way you won't be publishing bogus information.

Thanks for the report, feel free to ping me on any pull request you open.
