### ISSUE TITLE
fatal error: libphidgets/phidget21.h: No such file or directory compilation terminated

### ISSUE THREAD

**Issue by ShanLuo** [ros-drivers/phidgets_drivers#8]
I have installed the Phidgets libraries following the following link and the "Hello World" example was working. 
http://www.phidgets.com/docs/OS_-_Linux#Quick_Downloads

But when I install Phidgets ROS driver
https://github.com/ccny-ros-pkg/phidgets_drivers
I got the error 
fatal error: libphidgets/phidget21.h: No such file or directory compilation terminated.

How does it happy? The libraries have been installed by the Linux driver, right?

**Comment by mintar** [comment]
Hi @ShanLuo , https://github.com/ccny-ros-pkg/phidgets_drivers/issues/31 sounds like you solved your problem.

You don't need to install the library yourself from phidgets.com. You can also just do apt-get install ros-indigo-phidgets-drivers. And the ccny-ros-pkg repo is deprecated.
