### ISSUE TITLE
Phidgets Imu driver splits my tf tree

### ISSUE THREAD

**Issue by Oburshan** [ros-drivers/phidgets_drivers#87]
Hey, I am using phidgets imu 3/3/3 on google cartographer, and when i launch the imu driver it splits my tf tree which avoid cartographer node to provide a map because he don't have a complete tf tree.
The launch: `roslaunch phidgets_imu imu.launch`

Before Launching imu driver (Only cartographer node executed):
![Screenshot from 2021-03-25 08-01-55](https://user-images.githubusercontent.com/61157997/112426619-f1422780-8d40-11eb-8f95-9eeed08b7152.png)

And after:
![Screenshot from 2021-03-25 08-01-35](https://user-images.githubusercontent.com/61157997/112426653-fe5f1680-8d40-11eb-857d-697ae3b77715.png)

Thanks!

**Comment by Oburshan** [comment]
I solved it after removing the ImuFilterNodelet node from my launch file, i will close it now.

**Comment by mintar** [comment]
If you don't need the orientation, you can just remove the nodelet, as you just did. Alternatively, the ImuFilterNodelet has a parameter `publish_tf` that you should set to `false`.
