### ISSUE TITLE
imu_madgwick_filter should be added as a runtime dependency

### ISSUE THREAD

**Issue by gkouros** [ros-drivers/phidgets_drivers#9]
The imu_madgwick_filter nodelet is loaded in the [phidgets_imu/launch/imu.launch](https://github.com/ros-drivers/phidgets_drivers/blob/indigo/phidgets_imu/launch/imu.launch) launcher,
however it is not listed as a runtime dependency in package.xml .

**Comment by mintar** [comment]
Yes, I know. I never know what to do about this kind of dependencies. The `imu_filter_madgwick` package is not strictly required if you want to use `phidgets_imu`; the launch file is just one example of how to use it.

If I add a `run_depend` on `imu_filter_madgwick`, then the generated Debian package will depend on it, so you cannot install `ros-indigo-phidgets-imu` without installing `ros-indigo-imu-filter-madgwick`, even if you don't use it. It would be much nicer if there was a way in catkin to generate "recommends" dependencies in Debian packages: packages that you will probably need, but are not strictly required.

However, at least one other user has already stumbled upon this, so I'm going to add the dependency. Thanks!
