### ISSUE TITLE
Anyway to get this pkg to work with PhidgetSpatial Precision 3/3/3 ID: MOT0109_0

### ISSUE THREAD

**Issue by WorkingBones** [ros-drivers/phidgets_drivers#99]
Since all the old imus are discontinued is there any way to get this pkg to work with ROS

**Comment by clalancette** [comment]
It might; it depends on whether the `libphidgets22` library still supports it.  Does it?

**Comment by WorkingBones** [comment]
gonna be honest I have no idea. I am very new to ros

**Comment by clalancette** [comment]
> gonna be honest I have no idea. I am very new to ros

The libphidgets22 library is what is provided by https://www.phidgets.com/ in order to access their products.  If that library still supports your Phidget, then it will likely work with this package.  If it doesn't, then it will be significantly more difficult to make it work.
